org: fbielejec
app: shadow-cljs-serverless-demo
service: api

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 4000

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-2

functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.handler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true
